services:
    innmind_rest_server.controller.capabilities:
        class: Innmind\Rest\ServerBundle\Controller\CapabilitiesController
        arguments:
            - '@innmind_rest_server.definition.directories'
            - '@innmind_rest_server.routing.route_factory'
            - '@router'

    innmind_rest_server.controller.resource.options:
        class: Innmind\Rest\ServerBundle\Controller\Resource\OptionsController
        arguments:
            - '@innmind_rest_server.format'
            - '@serializer'

    innmind_rest_server.controller.resource.list:
        class: Innmind\Rest\ServerBundle\Controller\Resource\ListController
        arguments:
            - '@innmind_rest_server.format'
            - '@serializer'
            - '@innmind_rest_server.range_extractor'
            - '@innmind_rest_server.specification_builder'
            - '@innmind_rest_server.gateways'
            - '@innmind_rest_server.response.header_builder.list'

    innmind_rest_server.controller.resource.get:
        class: Innmind\Rest\ServerBundle\Controller\Resource\GetController
        arguments:
            - '@innmind_rest_server.format'
            - '@serializer'
            - '@innmind_rest_server.gateways'
            - '@innmind_rest_server.response.header_builder.get'

    innmind_rest_server.controller.resource.create:
        class: Innmind\Rest\ServerBundle\Controller\Resource\CreateController
        arguments:
            - '@innmind_rest_server.gateways'
            - '@serializer'
            - '@innmind_rest_server.format'
            - '@innmind_rest_server.response.header_builder.create'

    innmind_rest_server.controller.resource.update:
        class: Innmind\Rest\ServerBundle\Controller\Resource\UpdateController
        arguments:
            - '@innmind_rest_server.gateways'
            - '@serializer'
            - '@innmind_rest_server.format'
            - '@innmind_rest_server.response.header_builder.update'

    innmind_rest_server.controller.resource.remove:
        class: Innmind\Rest\ServerBundle\Controller\Resource\RemoveController
        arguments:
            - '@innmind_rest_server.gateways'
            - '@innmind_rest_server.response.header_builder.remove'

    innmind_rest_server.controller.resource.link:
        class: Innmind\Rest\ServerBundle\Controller\Resource\LinkController
        arguments:
            - '@innmind_rest_server.gateways'
            - '@innmind_rest_server.response.header_builder.link'
            - '@innmind_rest_server.translator.link'

    innmind_rest_server.controller.resource.unlink:
        class: Innmind\Rest\ServerBundle\Controller\Resource\UnlinkController
        arguments:
            - '@innmind_rest_server.gateways'
            - '@innmind_rest_server.response.header_builder.unlink'
            - '@innmind_rest_server.translator.link'
