services:
    innmind_rest_server.controller.capabilities:
        class: Innmind\Rest\ServerBundle\Controller\CapabilitiesController
        arguments:
            - '@innmind_rest_server.definition.directories'
            - '@innmind_rest_server.routing.route_factory'
            - '@router'

    innmind_rest_server.controller.resource:
        class: Innmind\Rest\ServerBundle\Controller\ResourceController
        arguments:
            - '@innmind_rest_server.format'
            - '@serializer'
            - '@innmind_rest_server.range_extractor'
            - '@innmind_rest_server.specification_builder'
            - '@innmind_rest_server.gateways'
            - '@innmind_rest_server.response.header_builder.list'
            - '@innmind_rest_server.response.header_builder.get'
