services:
    innmind_rest_server.response.header_builder.list_delegation:
        class: Innmind\Rest\Server\Response\HeaderBuilder\ListDelegationBuilder
        public: false

    innmind_rest_server.response.header_builder.list_content_type:
        class: Innmind\Rest\Server\Response\HeaderBuilder\ListContentTypeBuilder
        public: false
        arguments:
            - '@innmind_rest_server.formats.accept'
        tags:
            - { name: innmind_rest_server.response.header_builder.list }

    innmind_rest_server.response.header_builder.list_links:
        class: Innmind\Rest\Server\Response\HeaderBuilder\ListLinksBuilder
        public: false
        tags:
            - { name: innmind_rest_server.response.header_builder.list }

    innmind_rest_server.response.header_builder.list_range:
        class: Innmind\Rest\Server\Response\HeaderBuilder\ListRangeBuilder
        public: false
        tags:
            - { name: innmind_rest_server.response.header_builder.list }

    innmind_rest_server.response.header_builder.get_delegation:
        class: Innmind\Rest\Server\Response\HeaderBuilder\GetDelegationBuilder
        public: false

    innmind_rest_server.response.header_builder.get_content_type:
        class: Innmind\Rest\Server\Response\HeaderBuilder\GetContentTypeBuilder
        public: false
        arguments:
            - '@innmind_rest_server.formats.accept'
        tags:
            - { name: innmind_rest_server.response.header_builder.get }

    innmind_rest_server.response.header_builder.create_delegation:
        class: Innmind\Rest\Server\Response\HeaderBuilder\CreateDelegationBuilder
        public: false

    innmind_rest_server.response.header_builder.create_content_type:
        class: Innmind\Rest\Server\Response\HeaderBuilder\CreateContentTypeBuilder
        public: false
        arguments:
            - '@innmind_rest_server.formats.accept'
        tags:
            - { name: innmind_rest_server.response.header_builder.create }

    innmind_rest_server.response.header_builder.create_location:
        class: Innmind\Rest\Server\Response\HeaderBuilder\CreateLocationBuilder
        public: false
        tags:
            - { name: innmind_rest_server.response.header_builder.create }

    innmind_rest_server.response.header_builder.update_delegation:
        class: Innmind\Rest\Server\Response\HeaderBuilder\UpdateDelegationBuilder
        public: false

    innmind_rest_server.response.header_builder.remove_delegation:
        class: Innmind\Rest\Server\Response\HeaderBuilder\RemoveDelegationBuilder
        public: false

    innmind_rest_server.response.header_builder.link_delegation:
        class: Innmind\Rest\Server\Response\HeaderBuilder\LinkDelegationBuilder
        public: false

    innmind_rest_server.response.header_builder.unlink_delegation:
        class: Innmind\Rest\Server\Response\HeaderBuilder\UnlinkDelegationBuilder
        public: false
