services:
    innmind_rest_server.http.factory.header.accept_charset:
        class: Innmind\Http\Factory\Header\AcceptCharsetFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: accept-charset }

    innmind_rest_server.http.factory.header.accept_encoding:
        class: Innmind\Http\Factory\Header\AcceptEncodingFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: accept-encoding }

    innmind_rest_server.http.factory.header.accept:
        class: Innmind\Http\Factory\Header\AcceptFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: accept }

    innmind_rest_server.http.factory.header.accept_language:
        class: Innmind\Http\Factory\Header\AcceptLanguageFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: accept-language }

    innmind_rest_server.http.factory.header.accept_ranges:
        class: Innmind\Http\Factory\Header\AcceptRangesFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: accept-ranges }

    innmind_rest_server.http.factory.header.age:
        class: Innmind\Http\Factory\Header\AgeFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: age }

    innmind_rest_server.http.factory.header.allow:
        class: Innmind\Http\Factory\Header\AllowFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: allow }

    innmind_rest_server.http.factory.header.authorization:
        class: Innmind\Http\Factory\Header\AuthorizationFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: authorization }

    innmind_rest_server.http.factory.header.cache_control:
        class: Innmind\Http\Factory\Header\CacheControlFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: cache-control }

    innmind_rest_server.http.factory.header.content_encoding:
        class: Innmind\Http\Factory\Header\ContentEncodingFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: content-encoding }

    innmind_rest_server.http.factory.header.content_language:
        class: Innmind\Http\Factory\Header\ContentLanguageFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: content-language }

    innmind_rest_server.http.factory.header.content_length:
        class: Innmind\Http\Factory\Header\ContentLengthFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: content-length }

    innmind_rest_server.http.factory.header.content_location:
        class: Innmind\Http\Factory\Header\ContentLocationFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: content-location }

    innmind_rest_server.http.factory.header.content_range:
        class: Innmind\Http\Factory\Header\ContentRangeFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: content-range }

    innmind_rest_server.http.factory.header.content_type:
        class: Innmind\Http\Factory\Header\ContentTypeFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: content-type }

    innmind_rest_server.http.factory.header.date:
        class: Innmind\Http\Factory\Header\DateFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: date }

    innmind_rest_server.http.factory.header.expires:
        class: Innmind\Http\Factory\Header\ExpiresFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: expires }

    innmind_rest_server.http.factory.header.host:
        class: Innmind\Http\Factory\Header\HostFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: host }

    innmind_rest_server.http.factory.header.if_modified_since:
        class: Innmind\Http\Factory\Header\IfModifiedSinceFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: if-modified-since }

    innmind_rest_server.http.factory.header.if_unmodified_since:
        class: Innmind\Http\Factory\Header\IfUnmodifiedSinceFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: if-unmodified-since }

    innmind_rest_server.http.factory.header.last_modified:
        class: Innmind\Http\Factory\Header\LastModifiedFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: last-modified }

    innmind_rest_server.http.factory.header.link:
        class: Innmind\Http\Factory\Header\LinkFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: link }

    innmind_rest_server.http.factory.header.location:
        class: Innmind\Http\Factory\Header\LocationFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: location }

    innmind_rest_server.http.factory.header.range:
        class: Innmind\Http\Factory\Header\RangeFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: range }

    innmind_rest_server.http.factory.header.referrer:
        class: Innmind\Http\Factory\Header\ReferrerFactory
        tags:
            - { name: innmind_rest_server.http_header_factory, alias: referer }

    innmind_rest_server.http.factory.header.default:
        class: Innmind\Http\Factory\Header\TryFactory
        factory:
            - '@innmind_rest_server.http.factory.header_factory'
            - make

    innmind_rest_server.http.factory.header_factory:
        class: Innmind\Rest\ServerBundle\Factory\HeaderFactoryFactory
        public: false

    innmind_rest_server.http.request.verifier:
        class: Innmind\Rest\Server\Request\Verifier\DelegationVerifier
        public: false

    innmind_rest_server.http.request.verifier.accept:
        class: Innmind\Rest\Server\Request\Verifier\AcceptVerifier
        arguments:
            - '@innmind_rest_server.formats.accept'
        public: false
        tags:
            - { name: innmind_rest_server.http.request.verifier, priority: 100 }

    innmind_rest_server.http.request.verifier.content_type:
        class: Innmind\Rest\Server\Request\Verifier\ContentTypeVerifier
        arguments:
            - '@innmind_rest_server.formats.content_type'
        public: false
        tags:
            - { name: innmind_rest_server.http.request.verifier, priority: 75 }

    innmind_rest_server.http.request.verifier.range:
        class: Innmind\Rest\Server\Request\Verifier\RangeVerifier
        public: false
        tags:
            - { name: innmind_rest_server.http.request.verifier, priority: 50 }

    innmind_rest_server.http.request.verifier.link:
        class: Innmind\Rest\ServerBundle\Request\Verifier\LinkVerifier
        arguments:
            - '@router'
        public: false
        tags:
            - { name: innmind_rest_server.http.request.verifier, priority: 25 }
