services:
    innmind_rest_server.listener.exception:
        class: Innmind\Rest\ServerBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest_server.listener.generate_http_exception_response:
        class: Innmind\Rest\ServerBundle\EventListener\GenerateHttpExceptionResponseListener
        arguments:
            - '%kernel.debug%'
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest_server.listener.definition_loader:
        class: Innmind\Rest\ServerBundle\EventListener\DefinitionLoaderListener
        arguments:
            - '@innmind_rest_server.definition.locator'
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest_server.listener.translate_request:
        class: Innmind\Rest\ServerBundle\EventListener\TranslateRequestListener
        arguments:
            - '@innmind_rest_server.translator.request'
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest_server.listener.translate_response:
        class: Innmind\Rest\ServerBundle\EventListener\TranslateResponseListener
        arguments:
            - '@innmind_rest_server.translator.response'
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest_server.listener.request_verifier:
        class: Innmind\Rest\ServerBundle\EventListener\RequestVerifierListener
        arguments:
            - '@innmind_rest_server.http.request.verifier'
        tags:
            - { name: kernel.event_subscriber }
