services:
    innmind_rest_server.range_extractor.delegation:
        class: Innmind\Rest\Server\RangeExtractor\DelegationExtractor
        public: false

    innmind_rest_server.range_extractor.header:
        class: Innmind\Rest\Server\RangeExtractor\HeaderExtractor
        public: false
        tags:
            - { name: innmind_rest_server.range_extractor }

    innmind_rest_server.range_extractor.query:
        class: Innmind\Rest\Server\RangeExtractor\QueryExtractor
        public: false
        tags:
            - { name: innmind_rest_server.range_extractor }
