services:
    innmind_rest_server.serializer.normalizer.definition:
        class: Innmind\Rest\Server\Serializer\Normalizer\DefinitionNormalizer
        tags:
            - { name: serializer.normalizer }

    innmind_rest_server.serializer.normalizer.identities:
        class: Innmind\Rest\Server\Serializer\Normalizer\IdentitiesNormalizer
        tags:
            - { name: serializer.normalizer }

    innmind_rest_server.serializer.normalizer.resource:
        class: Innmind\Rest\Server\Serializer\Normalizer\HttpResourceNormalizer
        tags:
            - { name: serializer.normalizer }

    innmind_rest_server.serializer.encoder.json:
        class: Innmind\Rest\Server\Serializer\Encoder\JsonEncoder
        tags:
            - { name: serializer.encoder }

    innmind_rest_server.serializer.encoder.form:
        class: Innmind\Rest\Server\Serializer\Encoder\FormEncoder
        tags:
            - { name: serializer.encoder }
